apiVersion: v1
data:
  KEYCLOAK_AUTH_SERVER_URL: https://sso-sso-evil.10.40.2.222.nip.io/auth
  rhoarRaffleCreateEntryUrl: http://sourcedevil-th1-raffle-api-sourcedevil-th1-raffle-api.apps.us-west-1.starter.openshift-online.com/raffle/raffle/go
  rhoarRaffleWinnerUrl: http://sourcedevil-th1-raffle-api-sourcedevil-th1-raffle-api.apps.us-west-1.starter.openshift-online.com/raffle/raffle/
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app: rhoar-swarm-gateway-jwt
    group: com.sourcedevil.ref.rhoar.swarm.gateway.jwt
    provider: fabric8
    version: "1.0"
  name: rhoar-swarm-gateway-jwt
