spec:
  replicas: 1
  template:
    spec:
      containers:
      - env:        
         - name: rhoarRecurringpaymentsUrl
           valueFrom:
             configMapKeyRef:
               key: rhoarRecurringpaymentsUrl
               name: rhoar-api-gateway-cm
         - name: rhoarHwUrl
           valueFrom:
             configMapKeyRef:
               key: rhoarHwUrl
               name: rhoar-api-gateway-cm       
         - name: KEYCLOAK_AUTH_SERVER_URL
           valueFrom:
             configMapKeyRef:
               key: KEYCLOAK_AUTH_SERVER_URL
               name: rhoar-api-gateway-cm                                   
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 512Mi